version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: node:14.14.0
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn run build
      - run:
          name: test
          command: yarn test
      - run:
          name: lint
          command: yarn run lint
